---

version: '3.3'

services:
  db:

    build:
      context: '.'
      dockerfile: './Dockerfile-postgres'

    ports:
      - '5432:5432'

    restart: 'always'

    environment:
      POSTGRES_USER: 'jungle'
      POSTGRES_PASSWORD: 'password'

